/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type FWT_LoadTickets_Models_LoadTicketQueryModel = {
    ticketKey?: number;
    tenantID?: string | null;
    ticketNumber?: number;
    ticketDate?: string;
    ticketDateTime?: string | null;
    truckID?: string | null;
    orderNumber?: number;
    customerID?: string | null;
    customerName?: string | null;
    productID?: string | null;
    productDescription?: string | null;
    unitOfMeasure?: string | null;
    regionName?: string | null;
    locationName?: string | null;
    yardName?: string | null;
    grossWeight?: number | null;
    tareWeight?: number | null;
    netWeight?: number;
    operator?: string | null;
    job?: string | null;
    phase?: string | null;
    costType?: string | null;
    haulerID?: string | null;
    haulerName?: string | null;
    void?: boolean;
    invoiceNum?: number | null;
    invoiceDate?: string | null;
    truckKey?: number;
    orderKey?: number;
    customerKey?: number;
    batchNum?: string | null;
    materialAmount?: number | null;
    freightAmount?: number | null;
    surchargeAmount?: number | null;
    materialTax?: number | null;
    freightTax?: number | null;
    surchargeTax?: number | null;
    revised?: boolean | null;
    pdfBlobKey?: string | null;
    unitPrice?: number;
    surcharge?: number;
    freightRate?: number | null;
    udF1?: string | null;
    udF2?: string | null;
    udF3?: string | null;
    imageBlobKey?: string | null;
    signatureBlobKey?: string | null;
    manualWeight?: boolean | null;
    productKey?: number;
    materialTax2?: number | null;
    freightTax2?: number | null;
    surchargeTax2?: number | null;
    poNumber?: string | null;
    orderDescription?: string | null;
    hasNote?: boolean | null;
    taxCodeKey?: number | null;
    taxCode?: string | null;
    hasAdjustments?: boolean;
    readonly hasPDF?: boolean;
    readonly hasImage?: boolean;
    readonly hasSignature?: boolean;
    readonly ticketDateTimeCorrected?: string | null;
    readonly calculatedUnitPrice?: number;
};
